spring:
  datasource:
    url: jdbc:mysql://localhost/trazar?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop.dsx-++++++++++++++++++++++                                                                                                                                                             
    database-platform: org.hibernate.dialect.MySQL57Dialect

    properties:
      hibernate:
        show_sql: true
        format_sql: true



